[build]
  publish = "league-quiz-app/dist/league-quiz-app/browser"
  command = "npm install && npm run build --prefix league-quiz-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
