name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js with the correct version
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19' # Use an LTS version of Node.js

    # Step 3: Install Angular CLI globally
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    # Step 4: Install Netlify CLI globally
    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    # Step 5: Install project dependencies
    - name: Install dependencies
      working-directory: league-quiz-app
      run: npm install

    # Step 6: Build the Angular app with production configuration
    - name: Build the Angular app
      working-directory: league-quiz-app
      run: ng build --configuration=production

    # Step 7: Deploy to Netlify
    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: netlify deploy --prod --dir dist/league-quiz-app
